[build]
  functions = "functions"
  publish = "public"

[functions]
  directory = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/api/health"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/api/"
  status = 200

[build.environment]
  NODE_VERSION = "18" 